# Site settings
title: Beld
SEOTitle: 刘鼎的博客 | Beld's Blog
header-img: img/home-bg.jpg
email: hardstriver@gmail.com
description: "TUM Student | 这里是 @beld 的个人博客，与你一起发现更大的世界。"
keyword: "刘鼎"
url: ""              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'



# SNS settings
RSS: false
weibo_username:     hardstriver
github_username:    beld
instagram_username: hardstriver
linkedin_username: 	ihaiyang
#twitter_username:  huxpro
facebook_username:  hardstriver



# Build settings
highlighter: pygments
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# # Disqus settings
disqus_username: beldblog

# Duoshuo settings
# duoshuo_username: beld
# Share component is depend on Comment so we can NOT use share only.
# duoshuo_share: false                    # set to false if you want to use Comment without Sharing




# Analytics settings
# Baidu Analytics
#ba_track_id: 4cc1f2d8f3067386cc5cdb626a202900
# Google Analytics
#ga_track_id: 'UA-49627206-1'            # Format: UA-xxxxxx-xx
#ga_domain: huangxuan.me



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "Stay awesome!"
sidebar-avatar: /img/avatar_beld.png      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 0              # A tag will be featured if the size of it is more than this condition value



# Friends
# friends: [
#     {
#         title: "天镶的博客",
#         href: "http://lingyu.wang/"
#     },{
#         title: "Luke的自留地",
#         href: "http://hmqk1995.github.io"
#     },{
#         title: "SmdCn's Blog",
#         href: "http://blog.smdcn.net"
#     },{
#         title: "解旻的博客",
#         href: "http://xieminis.me/"
#     },{
#         title: "DHong Say",
#         href: "http://dhong.co"
#     },{
#         title: "尹峰以为",
#         href: "http://ingf.github.io/"
#     }
# ]
